---
# tasks file for common
- name: Generate config
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf.j2
  notify: reload nginx
  tags: configuration

- name: RemoveDefaultSite
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
