---
# tasks file for nginx
    - name: Add Nginx apt_key
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present
        
    - name: Configure Nginx repo on Ubuntu
      apt_repository:
        filename: nginx
        repo: "{{ item }}"
        update_cache: yes
        mode: 0644
      loop:
          - "deb [arch=amd64] https://nginx.org/packages/mainline/{{ ansible_facts['distribution'] | lower }}/ {{ ansible_facts['distribution_release'] }} nginx"
          - "deb-src https://nginx.org/packages/mainline/{{ ansible_facts['distribution'] | lower }}/ {{ ansible_facts['distribution_release'] }} nginx"

    - name: Install Nginx on Ubuntu
      apt:
        update_cache: yes      
        name:  "nginx={{ nginx_ver }}"
        state: present
      notify: run nginx